server:
  port: 8090

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: certificate-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6388

eureka:
  client:
    enabled: false

kafka:
  certificate-issuance: certificate-issuance-topic

jasper:
  report-template-directories:
    reportsDir: classpath:templates/