server:
  port: 8090

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: certificate-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: postgres
    password: 1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


eureka:
  client:
    enabled: false

# Бизнес-топики
kafka:
  certificate-issuance: certificate-issuance-topic

user:
  service:
    url: http://localhost:8081

notification:
  service:
    url: http://localhost:8082

course:
  service:
    url: http://localhost:8084

cert-directory: C:/certificates/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
    use-root-path: true
  model-converters:
    pageable-converter:
      enabled: true